# Sponsorship and funding options
# This file displays sponsorship options on the GitHub repository

# GitHub Sponsors
github: [maintainer]

# Patreon
patreon: null

# Open Collective
open_collective: null

# Ko-fi
ko_fi: null

# Tidelift
tidelift: null

# Community Bridge
community_bridge: null

# Liberapay
liberapay: null

# Issuehunt
issuehunt: null

# Buy me a coffee
buy_me_a_coffee: null

# Supabase
supabase: null

# Custom URL for donations
custom: null
